name: Test Reports
description: An opinionated test reporter for GitHub Actions
author: Callum Kerson

branding:
  icon: check-circle
  color: green

inputs:
  token:
    description: Token used to set commit statuses, which needs statuses write permission
    required: true
    default: ${{ github.token }}

runs:
  using: node24
  main: dist/index.js
